---
title: "Worksheet4"
author: "Dafnie Jayne Benajiba"
date: "2024-10-15"
output: pdf_document
---

#1A
```{r}
data <- data.frame(
  Shoe_Size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.75, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
)
data

```

#1-B
```{r}

females <- subset(data, Gender == "F", select = c(Shoe_Size, Height))
females


males <- subset(data, Gender == "M", select = c(Shoe_Size, Height))
males

```

#1-C 
```{r}
mean_shoe_size <- mean(data$Shoe_Size)
mean_shoe_size

mean_height <- mean(data$Height)
mean_height
```


#2. 
```{r}
Months <- c("March", "April", "JAnuary", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "Febraury", "May", "Augsut")
factor_Months <- factor(Months)
factor_Months
```

#3
```{r}
summary(Months)
summary(factor_Months)


```

#4
```{r}

directions <- c("East", "West", "North")
frequency <- c(1, 4, 3)

new_order_data <- factor(directions, levels = c("East", "West", "North"))
print(new_order_data)

table_data <- data.frame(Direction = new_order_data, Frequency = frequency)
print(table_data)


```


#5
```{r}
data <- read.table ("~/RBasics/CS101_DataScience/worksheet4a/import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(data)

```

#6

```{r}
snack_price <- readline(prompt = "Enter the price of the snack (must be divisible by 50): ")
snack_price <- as.integer(snack_price)

if (is.na(snack_price)) {
  cat("Invalid input. Please enter a numeric value.\n")
} else {
  minimum_bills <- function(price) {
    bills <- c(1000, 500, 200, 100, 50)
    count <- 0
    
    for (bill in bills) {
      if (price >= bill) {
        count <- count + (price %/% bill)
        price <- price %% bill
      }
    }
    
    return(count)
  }
  
  cat("Minimum number of bills needed:", minimum_bills(snack_price), "\n")
}


```
#7
```{r}
snack_price <- readline(prompt = "Enter the price of the snack (must be divisible by 50): ")
snack_price <- as.integer(snack_price)

if (is.na(snack_price) || snack_price %% 50 != 0) {
  cat("Invalid input. Please enter a numeric value that is divisible by 50.\n")
} else {
  minimum_bills <- function(price) {
    bills <- c(1000, 500, 200, 100, 50)
    count <- 0
    
    for (bill in bills) {
      if (price >= bill) {
        count <- count + (price %/% bill)
        price <- price %% bill
      }
    }
    
    return(count)
  }
  
  cat("Minimum number of bills needed:", minimum_bills(snack_price), "\n")
}

```

#8.a
```{r}
data <- data.frame(
  Name = c("Annie", " Thea", "Steve", "Hanna"),
  Grade1 = c(85, 75, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90))
data


```

#8.B
```{r}
for (i in 1:nrow(data)) {
  avg_score <- sum(data[i, 2:5]) / 4  
  
  if (avg_score >= 88.75) {
    cat(data$Name[i], "'s average grade this semester is", avg_score, "\n")
  }
}

```
#8.C
```{r}
for (i in 1:nrow(data)) {
  avg_score <- sum(data[i, 2:5]) / 4  
  
  if (avg_score >= 88.75) {
    cat(data$Name[i], "'s average grade this semester is", avg_score, "\n")
  }
}

```
#8.D
```{r}
results <- c()

for (i in 1:nrow(data)) {
  highest_score <- 0  
  
  for (j in 2:ncol(data)) {
    if (data[i, j] > highest_score) {
      highest_score <- data[i, j]  
    }
  }
  
  if (highest_score > 90) {
    results <- c(results, paste(data$Name[i], "’s highest grade this semester is", highest_score))
  }
}

cat(results, "\n")


```
